name: TokenAPI
main: onebone\pointapi\PointAPI
api: [3.11.1, 3.11.3, 3.11.4, 3.11.5]
version: 2.0.9
author: onebone | Edit By AlexItz16
permissions:
 pointapi.*:
  default: op
  description: Allows to control all of functions in PointAPI
  children:
   pointapi.command.*:
    default: op
    description: Allows to use all of commands in PointAPI
    children:
     pointapi.command.setpoint:
      default: op
      description: Allows to set player's point
     pointapi.command.mypoint:
      description: Allows player to see his/her point
      default: op
     pointapi.command.givepoint:
      description: Allows player to give point to others
      default: op
     pointapi.command.pay:
      description: Allows player to pay to someone
      default: true
     pointapi.command.seepoint:
      description: Allows player to see others' point
      default: true
     pointapi.command.setlang:
      description: Allows player to set his/her language
      default: true
     pointapi.command.toppoint:
      description: Allows player to see top point list
      default: true
     pointapi.command.mystatus:
      description: Allows player to see his/her financial status
      default: true
     pointapi.command.takepoint:
      description: Allows player to take point from others
      default: op
